### PR TITLE
refactor to vanilla js

### PR DESCRIPTION
**Pull request by louisbuchbinder**

### CODE REVIEW

**Comment by jimeh** [comment]
Thanks :)

**Comment by louisbuchbinder** [comment]
@jimeh 👍  Was the Travis build supposed to ```npm publish``` or does that need to be done manually?

**Comment by jimeh** [comment]
@louisbuchbinder sorry, yes that does need to be done manually. I'll publish a new version now in a bit :)

**Comment by louisbuchbinder** [comment]
Right on!

**Pull request merged**
